import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import Footer from "@/components/Footer";
import DarkNavbar from "@/components/DarkNavbar";
import LightNavbar from "@/components/LightNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ecommerce Store (Nasir)",
  description: "Ecommerce Store Quarter 2 Hackathon Generated by nasir",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DarkNavbar />
        <LightNavbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
